"use client"

import { useId, useState } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Field, FieldLabel } from "@/components/ui/field"
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog"
import NotificationItem from "./notification-item"

type Role = "traveler" | "guide" | "owner" | "manager" | "member"
type Category = "booking" | "payment" | "verification"
type Example = { id: string; category: Category; title: string; description: string; detail: string; at: string; roles: Role[]; context: "individual" | "group" | "account" | "both"; href?: string; action?: string }
const PROVIDERS: Role[] = ["guide", "owner", "manager", "member"]
const OPERATORS: Role[] = ["traveler", "guide", "owner", "manager"]
const EXAMPLES: Example[] = [
  { id: "confirmed", category: "booking", title: "Booking terkonfirmasi", description: "Pembayaran pertama berhasil dalam masa tahan. Keberangkatan Rinjani sudah terkonfirmasi.", detail: "Booking tidak menunggu persetujuan manual pemandu. Periksa tanggal, peserta, dan rencana pada detail booking. Ini peristiwa contoh, bukan hasil checkout sesi ini.", at: "3 Oktober, 10.00 WIB", roles: [...OPERATORS, "member"], context: "both", href: "/booking/preview", action: "Tinjau booking contoh" },
  { id: "deadline", category: "payment", title: "Pelunasan DP perlu ditinjau", description: "Sisa pembayaran perlu dilunasi melalui QRIS AturTrip sebelum tenggat pada booking.", detail: "Biaya layanan sudah dibayar pada transaksi pertama. Jika sisa DP tidak lunas saat tenggat, booking batal otomatis dan refund mengikuti snapshot template. Nominal dan tenggat sebenarnya harus berasal dari API.", at: "3 Oktober, 09.30 WIB", roles: OPERATORS, context: "both", href: "/booking/preview", action: "Tinjau pelunasan contoh" },
  { id: "refund", category: "payment", title: "Status refund diperbarui", description: "Refund contoh menunggu penyelesaian. Periksa kanal QRIS asli atau tujuan alternatif terverifikasi.", detail: "Transfer yang gagal tidak menghilangkan hak refund. Pembatalan pemandu memberi refund penuh termasuk biaya layanan; pembatalan sukarela memakai snapshot syarat. Tidak ada dana yang diproses pada halaman ini.", at: "3 Oktober, 09.00 WIB", roles: OPERATORS, context: "both", href: "/booking/preview", action: "Tinjau simulasi refund" },
  { id: "reschedule", category: "booking", title: "Permintaan jadwal baru", description: "Jadwal lama tetap berlaku selama usulan reschedule belum disetujui.", detail: "Slot baru perlu diperiksa sebelum disetujui. Permintaan wisatawan tidak menaikkan batas refund atau memundurkan tenggat DP; usulan pemandu mengikuti aturan tersendiri. Tidak ada respons bukan persetujuan.", at: "3 Oktober, 08.45 WIB", roles: [...OPERATORS, "member"], context: "group", href: "/booking/preview?trip=group-1-1&slot=evening&participants=2&payment=full", action: "Tinjau booking grup contoh" },
  { id: "replacement", category: "booking", title: "Tim pemandu grup diperbarui", description: "Wisatawan menerima identitas publik pemandu pengganti dan dapat meninjau tim.", detail: "Pengganti wajib terverifikasi dan tidak bentrok. Notifikasi hanya memuat informasi publik; KTP/swafoto tidak dikirim. Tim pada tautan ini contoh, bukan pergantian pada booking nyata.", at: "3 Oktober, 08.30 WIB", roles: ["traveler", "owner", "manager", "member"], context: "group", href: "/groups/1/trips/1", action: "Lihat tim publik contoh" },
  { id: "dispute", category: "booking", title: "Sengketa sedang ditinjau", description: "Status sengketa contoh terlihat pada booking; dana terkait menunggu keputusan.", detail: "Pengajuan biasa tersedia hingga 48 jam setelah waktu selesai final. Kelengkapan bukti, akses pihak terkait, dan penahanan dana diputuskan melalui API. Halaman ini tidak membuat laporan atau sengketa nyata.", at: "2 Oktober, 16.00 WIB", roles: OPERATORS, context: "group", href: "/booking/preview?trip=group-1-1&slot=evening&participants=2&payment=full", action: "Tinjau sengketa contoh" },
  { id: "identity", category: "verification", title: "Identitas perlu diperbaiki", description: "Swafoto contoh kurang jelas. Periksa alasan dan kirim ulang dokumen sesuai arahan.", detail: "Hasil verifikasi diterima melalui aplikasi dan email pemandu. Dokumen tetap privat; identitas disetujui belum menggantikan review setiap listing baru.", at: "2 Oktober, 14.00 WIB", roles: PROVIDERS, context: "account", href: "/account/kyc", action: "Tinjau verifikasi contoh" },
  { id: "listing", category: "verification", title: "Listing menunggu revisi", description: "Jelaskan perlengkapan yang tidak termasuk dan periksa kembali titik temu.", detail: "Staf memberikan alasan, bukan mengubah isi listing langsung. Versi aktif lama tetap berlaku selama usulan penting menunggu persetujuan. Buka wizard untuk meninjau simulasi respons review.", at: "2 Oktober, 13.00 WIB", roles: ["guide", "owner", "manager"], context: "both", href: "/guide-mode/listing", action: "Tinjau wizard contoh" },
  { id: "payout", category: "payment", title: "Permintaan pencairan ditinjau", description: "Saldo dalam permintaan contoh belum dapat diminta untuk kedua kalinya.", detail: "Hanya pemandu individu/pemilik grup dapat meminta pencairan. Persetujuan superadmin dan hasil transfer mitra belum terintegrasi; tidak ada saldo atau transfer nyata di sini.", at: "2 Oktober, 11.00 WIB", roles: ["guide", "owner"], context: "both" },
]
const ROLE_OPTIONS = [{ value: "traveler", label: "Wisatawan" }, { value: "guide", label: "Pemandu individu" }, { value: "owner", label: "Pemilik grup" }, { value: "manager", label: "Pengelola grup" }, { value: "member", label: "Pemandu anggota" }]

export function NotificationInbox() {
  const id = useId()
  const [role, setRole] = useState<Role>("traveler")
  const [category, setCategory] = useState("all")
  const [onlyUnread, setOnlyUnread] = useState(false)
  const [read, setRead] = useState<string[]>([])
  const [selected, setSelected] = useState<Example | null>(null)
  const [empty, setEmpty] = useState(false)
  const groupRole = role === "owner" || role === "manager" || role === "member"
  const items = empty ? [] : EXAMPLES.filter(item => item.roles.includes(role) && (role === "traveler" || item.context === "account" || item.context === "both" || item.context === (groupRole ? "group" : "individual"))).map(item => ({ ...item, href: groupRole && item.context === "both" && item.href === "/booking/preview" ? "/booking/preview?trip=group-1-1&slot=evening&participants=2&payment=full" : item.href }))
  const isRead = (item: Example) => read.includes(`${role}:${item.id}`)
  const unread = items.filter(item => !isRead(item)).length
  const matches = items.filter(item => (category === "all" || item.category === category) && (!onlyUnread || !isRead(item)))
  function markRead(item: Example) { setRead(current => [...new Set([...current, `${role}:${item.id}`])]) }
  return <main className="flex flex-col gap-5 px-5 py-6"><Badge variant="secondary" className="w-fit">Kotak masuk contoh</Badge><div><h1 className="font-heading text-2xl font-extrabold">Notifikasi</h1><p className="mt-2 text-sm text-muted-foreground" role="status">{unread} belum dibaca · {ROLE_OPTIONS.find(option => option.value === role)?.label}</p></div><Alert><AlertDescription>Peristiwa dan status dibaca hanya contoh lokal, terpisah dari checkout/editor. Tidak ada WhatsApp atau email yang dikirim. Muat ulang memulihkan daftar awal.</AlertDescription></Alert>
    <Field><FieldLabel htmlFor={id}>Tinjau sebagai peran contoh</FieldLabel><Select value={role} onValueChange={value => { setRole(value as Role); setSelected(null); setCategory("all"); setOnlyUnread(false) }}><SelectTrigger id={id} className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{ROLE_OPTIONS.map(option => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectGroup></SelectContent></Select></Field>
    <p className="text-xs text-muted-foreground">{groupRole ? "Konteks grup contoh. Pengelola/anggota tidak mendapat pemberitahuan pencairan." : role === "guide" ? "Konteks pemandu individu contoh." : "Booking wisatawan contoh, termasuk perjalanan grup."} Pilihan peran ini tidak memberikan izin akun/API.</p>
    <ToggleGroup type="single" variant="outline" className="flex flex-wrap" value={category} onValueChange={value => { if (value) setCategory(value) }} aria-label="Kategori notifikasi"><ToggleGroupItem value="all">Semua</ToggleGroupItem><ToggleGroupItem value="booking">Pemesanan</ToggleGroupItem><ToggleGroupItem value="payment">Pembayaran</ToggleGroupItem><ToggleGroupItem value="verification">Verifikasi</ToggleGroupItem></ToggleGroup>
    <div className="flex flex-wrap gap-2"><Button size="sm" variant={onlyUnread ? "default" : "outline"} onClick={() => setOnlyUnread(value => !value)} aria-pressed={onlyUnread}>Belum dibaca</Button><Button size="sm" variant="ghost" disabled={!unread} onClick={() => setRead(current => [...new Set([...current, ...items.map(item => `${role}:${item.id}`)])])}>Tandai semua dibaca</Button></div>
    {matches.length ? <div className="flex flex-col gap-3">{matches.map(item => <button type="button" key={item.id} className="w-full rounded-4xl text-left outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50" aria-label={`${item.title}${isRead(item) ? ", sudah dibaca" : ", belum dibaca"}`} onClick={() => { setSelected(item); markRead(item) }}><NotificationItem variant={item.category} title={item.title} description={item.description} time={item.at} unread={!isRead(item)} /></button>)}</div> : <Alert><AlertTitle>{empty ? "Belum ada notifikasi" : "Tidak ada notifikasi yang cocok"}</AlertTitle><AlertDescription>{empty ? "Pembaruan pesanan, pembayaran, dan hasil tinjauan akan muncul di sini." : "Semua sudah dibaca atau kategori ini belum memiliki contoh untuk peran terpilih."}</AlertDescription></Alert>}
    <Button variant="ghost" onClick={() => { setEmpty(value => !value); setCategory("all"); setOnlyUnread(false) }}>{empty ? "Pulihkan daftar contoh" : "Tinjau keadaan kosong"}</Button>
    <Dialog open={!!selected} onOpenChange={open => { if (!open) setSelected(null) }}><DialogContent className="max-h-[85dvh] overflow-y-auto">{selected && <><DialogHeader><DialogTitle>{selected.title}</DialogTitle><DialogDescription>{selected.at} · peristiwa contoh</DialogDescription></DialogHeader><p className="text-sm leading-relaxed">{selected.detail}</p><div className="flex flex-wrap gap-2"><Badge variant="outline">Aplikasi · contoh</Badge><Badge variant="outline">{role === "traveler" ? "WhatsApp" : "Email"} · contoh belum dikirim</Badge></div><p className="text-xs text-muted-foreground">Menandai dibaca tidak berarti menyetujui jadwal/perubahan atau membayar tagihan. Tautan membuka contoh baru; status notifikasi dan halaman tujuan belum tersinkronisasi.</p><DialogFooter><Button variant="outline" onClick={() => { setRead(current => current.filter(key => key !== `${role}:${selected.id}`)); setSelected(null) }}>Tandai belum dibaca</Button>{selected.href && <Button asChild><Link href={selected.href}>{selected.action}</Link></Button>}</DialogFooter></>}</DialogContent></Dialog>
  </main>
}
